name: nlxos-showcase-kiosk # you probably want to 'snapcraft register <name>'
version: '1.1.2' # just for humans, typically '1.2+git' or '1.3.2'
summary: NALINV Showcase Snap # 79 char long summary
description: |
  NALINV's Showcase App, No.NSC001 

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
#base: core18

apps:
  nlxos-showcase-kiosk:
    daemon: simple
    restart-condition: always
    command: desktop-launch xwayland-kiosk-launch "$SNAP/app/nlxos-showcase-kiosk"
    environment:
      XWAYLAND_FULLSCREEN_WINDOW_HINT: window_role="browser-window"
    slots: [ x11 ]
    plugs:
      - browser-sandbox
      - network
      - network-bind
      - opengl
      - pulseaudio
      - wayland
      - x11-plug

plugs:
  browser-sandbox:
    interface: browser-support
    allow-sandbox: true
  x11-plug: # because cannot have identical plug/slot name in same yaml.
    interface: x11

parts:
  electron-app:
    source: app/
    plugin: nodejs
    node-engine: 10.15.0

    after:
      - desktop-gtk2
      - xwayland-kiosk-helper

    build: node_modules/.bin/electron-builder
    install: |
      mkdir $SNAPCRAFT_PART_INSTALL/app
      mv dist/linux-unpacked/* $SNAPCRAFT_PART_INSTALL/app
    prime:
      - -node_modules

    stage-packages:
      - libasound2
      - libgconf-2-4
      - libnss3
      - libxss1
      - libxtst6
